### ISSUE TITLE
Example for registering consumer and adding authorization (car-demo)

### ISSUE THREAD

**Issue by micskeiz** [arrowhead-f/sos-examples-spring#10]
The management UI is not compatible yet with version 4.1.3 of the framework, and it was not evident for me how the consumer registration and authorization can be done manually.

Maybe a short example can be added to the README. 

For example, in my experience for the demo-car, the followings have to be added manually to the arrowhead MySQL database (timestamps can be changed, they are only included here for samples).

- system_:`X, 'car_consumer_demo', 'localhost', '8080', '', '2019-10-22 13:24:00', '2019-10-22 14:06:43'`
- authorization_intra_cloud: `Q, '2019-10-22 13:23:00', '2019-10-22 13:23:00', X, Y, Z`
- authorization_intra_cloud: `R, '2019-10-22 13:23:00', '2019-10-22 13:23:00', X, Y, W`
- authorization_intra_cloud_interface_connection: `(id), Q, '2', '2019-10-22 13:23:00', '2019-10-22 13:23:00'`
- authorization_intra_cloud_interface_connection: `(id), R, '2', '2019-10-22 13:23:00', '2019-10-22 13:23:00'`

where
- X is the new ID got for car_consumer_demo
- Y is the id of car_provider_demo system (can be checked by querying the system_ table after starting the provider)
- Z is the id of the create-car service (in service_definition table)
- W is the id of the get-car service (in service_definition table) 
- R, Q are the ids for the manually created authorization rules
- (id) is a don't care unused id

(Is there a better way/tool to perform these steps?)

**Comment by borditamas** [comment]
Yes the management tool is not migrated yet but will be ready soon.
You can send the required json payload by the Swagger API of the actual core system. [Check this issue for more info about!](https://github.com/arrowhead-f/core-java-spring/issues/79) It's not a better just an other way.

Also thanks for your ReadMe related remark, we will update it as suggested.

**Comment by borditamas** [comment]
fixed by pull request #11
