### ISSUE TITLE
Trying to run the demo-car example

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/sos-examples-spring#15]
Hi,

I am trying to run the demo-car example following the instructions provided in README . While importing the certificate, I was getting the pop up as shown in the below image which asked me which certificate to use. I did choose car-demo-provider while I was running demo-provider example but I am getting an error that " SERVICE REGISTRY IS UNREACHABLE" as it is not part of the same certificate chain of trust and the same message appears for other systems as well. 
So my question is,
1. When do i have to use the certificate w.r.t provider and consumer 

2. While running Management tool which certificate do i need to use
![image](https://user-images.githubusercontent.com/44111991/71165172-b48ba480-2250-11ea-80dc-4a0d2fb5deb9.png)
![image](https://user-images.githubusercontent.com/44111991/71165212-c5d4b100-2250-11ea-8889-a2ee98d067f1.png)
![image](https://user-images.githubusercontent.com/44111991/71165260-d71dbd80-2250-11ea-85b9-b8c6f3ff3f13.png)
3. Am I missing some other configuration settings because as per application.properties I did set details according to https://github.com/arrowhead-f/client-skeleton-java-spring/blob/master/README.md#best-practices-to-start-with-the-skeletons

(Note: Management tool is working when I use sysop certificate)
![image](https://user-images.githubusercontent.com/44111991/71165357-02081180-2251-11ea-83cc-797b4e8f3a6c.png)

Thanks and regards,
Suman

**Comment by borditamas** [comment]
Hello,

you need to use the sysop certificate for the Management tool. The provider's and consumer's certificates are authorized by the core systems upon each and every https request. You have nothing to do with them.

You need to register the consumer [manually](https://github.com/arrowhead-f/sos-examples-spring#requirements) (the provider registrates itself automatically upon startup) and create the intra-cloud authorization rules.
Please note, that mgmt tool is still under development, therefore system registration by it is not yet available. As far as I remember auth rule creation is already available in mgmt tool, but I'm not sure.

**Comment by sumi0910** [comment]
Hi,
Thank you for the response and according to the reply if i go, then executing demo-car-provider-4.1.3.jar should lead to automatic registration of provider in mysql arrowhead_system database. But I am unable to reach Service Registry because of the certification issue. When I choose sysos certificate, I get "GOT" message in chrome but choosing demo-car-provider certificate gives an error as shown in the below screenshot.  Is it because of certification issue or where I need to look into to resolve it

![image](https://user-images.githubusercontent.com/44111991/71172595-ead12000-2260-11ea-982a-09636d818831.png)
![image](https://user-images.githubusercontent.com/44111991/71172611-f886a580-2260-11ea-9852-4ebdf1ab7161.png)

Thanks and regards,
suman

**Comment by borditamas** [comment]
It's definitely a certificate issue. Did you change the default certificates of the core systems?

**Comment by sumi0910** [comment]
Nope. I didn't and that's why when I choose sysop.testcloud2.aitia.arrowhead.eu, I am able to reach Service registry
![image](https://user-images.githubusercontent.com/44111991/71173804-f114cb80-2263-11ea-88c7-e2035c88f2c6.png)
![image](https://user-images.githubusercontent.com/44111991/71173888-2b7e6880-2264-11ea-80c2-dbbf716f94a6.png)

**Comment by sumi0910** [comment]
Hi, 
Am I supposed to change the default certificates?
Thanks,
Suman

**Comment by borditamas** [comment]
No you shouldn't if you want to test the car demo with the default certs. But according to your screenshot it has been changed. You are using sysop cert with `testcloud.user.arrowhead.eu` , but the car demo is using `testcloud2.aitia.arrowhead.eu` which is the default also in the core systems.

**Comment by sumi0910** [comment]
Now its weird. Because all i have in Your certificates under google chrome is testcloud2.aitia.arrowhead.eu but when I am accessing swagger UI, I see sysop cert with testcloud.user.arrowhead.eu

![image](https://user-images.githubusercontent.com/44111991/71253380-05ba9780-2328-11ea-99ca-7840c21ff9a2.png)

![image](https://user-images.githubusercontent.com/44111991/71253456-41556180-2328-11ea-9dc1-1a769fb3210b.png)

Can you tell me if I can change the certificate of core systems or certificate of car demo and accordingly make car demo working

**Comment by borditamas** [comment]
So if you having access to swagger with this changed certs (`testcloud.user.arrowhead.eu`) that means your core systems using that ones not the defaults. You should download the default certs again form the core-java-spring master/certificates/testcloud2 folder  and put them into your core systems folders -> src/main/resources/certificates. Also make sure that the applications.properties are in line with the cert path, password, etc... Finally you should re-compile the core systems with `mvn install`.

OR,

[you can create new certificates](https://github.com/arrowhead-f/core-java-spring#how-to-create-my-own-certificates) for the car consumer and provider from your current  (`testcloud.user.arrowhead.eu`) cloud cert.

**Comment by sumi0910** [comment]
Hey,
I did create the certificates from tstcloud.user.arrowhead.eu as shown in the below image , but still i am getting same issue ( Note: i replaced the certificates with the newer one that i created and also the trust store) 
![image](https://user-images.githubusercontent.com/44111991/71621822-ddf1ec00-2bd1-11ea-84bb-58975796368b.png)
![image](https://user-images.githubusercontent.com/44111991/71621857-20b3c400-2bd2-11ea-8512-ef8089328862.png)

**Comment by borditamas** [comment]
Hello,

1) according to your logs your are using `sysop.testcloud.user.arrowhead.eu` cert for car demo provider and not the `car_demo_provider.testcloud.user.arrowhead.eu` what you have created.  The system name validation won't work for sure.

2) please verify that your trust stores are containing the `testcloud.user.arrowhead.eu` cert regarding to each application and core systems.

Do not forget to run `mvn clean install` after you have replaced the certs.

**Comment by sumi0910** [comment]
Hello, 
 thanks for the command "mvn clean install", because of that the certificate was not getting used. 
Now as per the created self-signed certificate and the one which is used for the running of the core certificates, I find some differences and unable to understand how to change the status of testcloud from Keypair entry to a trusted certificate because the self-signed certificate which I created is unable to find 5 parts and accessing testcloud.p12 rather than accessing car_demo_provider.p12.

![image](https://user-images.githubusercontent.com/44111991/71673596-7d9dae80-2d79-11ea-9e4c-fd05be229378.png)

For the car_demo_provider, the self-signed client is generated from testcloud and the hierarchy is from master

![image](https://user-images.githubusercontent.com/44111991/71673999-6dd29a00-2d7a-11ea-834f-e85c12591f76.png)




For sysop.p12 which is used by core systems have the following difference w.r.t testcloud in terms of hierarchy .

![image](https://user-images.githubusercontent.com/44111991/71673947-5398bc00-2d7a-11ea-845c-7e2b872c7258.png)

**Comment by sumi0910** [comment]
Hello,

Thank you for the command mvn clean install, because of this the updated certificate was not being used. 

I added authorization rules using Swagger UI and did run demo-car example, but I am not sure whether the output I am receiving is valid or not because I was expecting the response as mentioned for the get-car (created authorization rules for this service)
![image](https://user-images.githubusercontent.com/44111991/71742226-4c001280-2e61-11ea-9b48-8d2e94ecc04e.png)

**Comment by borditamas** [comment]
You have got an "UnavailableServerException", meaning that the provider wasn't working on 127.0.0.1:8888 due to some reason.

**Comment by sumi0910** [comment]
hey,

![image](https://user-images.githubusercontent.com/44111991/71832083-7abcf980-30aa-11ea-995f-356fbaebfdcd.png)
even though the port is not assigned to any other application, it throws this error when i am running provider and I did try to change the port number and run it, same error still.

**Comment by borditamas** [comment]
Hello,
this issue is related to your own environment and not to arrowhead. Maybe your virtual machine have no access to the necesarry ports, but I don't know...
