### ISSUE TITLE
Issue compiling the examples

### ISSUE THREAD

**Issue by mistersound** [arrowhead-f/sos-examples-spring#17]
Hi,
I am trying to compile the examples but after executing mvn install, I am having the following error: 
"eu.arrowhead:demo-car-provider:jar:4.1.3: Failure to find eu.arrowhead:client-library:jar:4.1.3.13 in https://repo.maven.apache.org/maven2"
It looks like the dependency "client-libary is not available in maven repository. 
When Trying to download it and use a system scope, it still doesn't compile. 
Thanks for your help
Junior

**Comment by borditamas** [comment]
Hello,
yes it's not distributed via maven central. We are using Github Packages which have to be configured with maven. Under the requirements section in the ReadMe you can find the link for the confuguration guide.

Br, Tamás

**Comment by mistersound** [comment]
Thanks Tamás, 
that solved my issues. 
Junior
