### ISSUE TITLE
Can consumer register itself in system_?

### ISSUE THREAD

**Issue by marci543** [arrowhead-f/sos-examples-spring#19]
Car Provider can register itself in the `system_` table by [registering the service definition](https://github.com/arrowhead-f/sos-examples-spring/blob/e4a684285bb3c1ff8f7103c1a9b35931938653d1/demo-car/demo-car-provider/src/main/java/eu/arrowhead/client/skeleton/provider/ProviderApplicationInitListener.java#L87).
How should the consumer register itself? Is there an automatic way? I couldn't find it in the documentation.

**Comment by borditamas** [comment]
There is no automatic way at the moment, but the need is already on the develoment roadmap.

**Comment by borditamas** [comment]
Arrowhead v4.4.0 delivers this feature, but in this project the consumers are not webservres. Just starts and ends and since the authorization rules have to be adjusted anyway we've decided to not imlement it into these consumers.
