### ISSUE TITLE
Can't consume Car Provider - Get method from SoapUI

### ISSUE THREAD

**Issue by wsteven24** [arrowhead-f/sos-examples-spring#23]
As title says, I'm trying to send request to the Car Provider service through SoapUI but got a response error: 
```
{
   "errorMessage": "Unauthorized access: https://127.0.0.1:8888/car, no token is specified",
   "errorCode": 401,
   "exceptionType": "AUTH"
}
```

I've set the ssl certificate car_demo_provider.p12 on SoapUI, and set the authorization token (given from orchestrator/orchestration) in the request header. What am I missing? 
GET https://127.0.0.1:8888/car HTTP/1.1
Accept-Encoding: gzip,deflate
Authorization: Bearer TOKEN
Host: 127.0.0.1:8888
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.5 (Java/12.0.1)

BTW, the example goes well when executing from the jar consumer.

**Comment by borditamas** [comment]
Hello,

in the current versions the token is expected to being sent as a query parameter:  `https://127.0.0.1:8888/car?token={token}`

[The token access policy standardization is on our roadmap](https://github.com/eclipse-arrowhead/roadmap/issues/13), but not finalized yet.

**Comment by wsteven24** [comment]
Thank you! it's working now, both the post and get methods.
I'm just thinking it is a little weird to send the token as query parameter (out of standards)... Suscribing myself to that link you provided.
![image](https://user-images.githubusercontent.com/8584403/116976388-5b93a380-acc1-11eb-864b-7e98ce4764fc.png)

I'm clossing this issue.
