### ISSUE TITLE
Register provider system developed in .net using "Secure" : "TOKEN"

### ISSUE THREAD

**Issue by wsteven24** [arrowhead-f/sos-examples-spring#24]
Hello!

Is it possible to register and afterwards consume a provider system (which is developed in c# net) by setting the "secure": "TOKEN" in the registration? Or this is only posible for systems developed on arrowhead framework? 
I don't have it clear how that "secure":"TOKEN" flag works.  I've tried so, the orchestration process gives me a token, but once I pass it to the consumer, it returns an error saying the token is not valid (this message is a validation message from my c# provider system), so as workaround, I changed the flag to NOT_SECURE. Then, I generated a token manually from the provider (the token is generated from a user and password process) and finally I passed the token to the consumer making it work.

**Comment by borditamas** [comment]
Hello!

No matter what language and technology your application systems were written in. The token is a [JSON Web Token](https://jwt.io) and there are plenty of libraries you can use for different languages to dealing with. If a provider defines its security level to `TOKEN`, than it means, that during the orchestration process the Authorization Core System will create a JWT token encrypted with the provider's public key and the token's payload will contain a `consumer info`, the `serviceDefinition`, the `interface` and the `tokenDuration`. Also the token will be sigend by the Authorization Core Sytem, so at the end only the provider will be able to decrypt the token with its own private key and can verify it with the Authorization Core System's public key (provider can ask for it by consuming its `auth-public-key` service).

**Comment by wsteven24** [comment]
Thank you. According to your statement, it is needed to modify the provider system so that it can decrypt the token by using its private key. I've modified my csharp code and got the token decrypted. It looks like the following:

```
{
  "jti": "pfbzoSZpYtaQvVB3ajgefA",
  "iss": "Authorization",
  "iat": 1620909495,
  "nbf": 1620909435,
  "cid": "consumerxpertapi.testcloud2.aitia",
  "sid": "getallcustomers",
  "iid": "HTTP-SECURE-JSON"
}
```

The problem is that the provider as it was made, it reads the JWT and gets the userName, role, culture, and other stuff from it. My question: Is it possible to add this information in the token generation?

**Comment by wsteven24** [comment]
They answered my question on Slack. It is not possible to add claims to the arrowhead's token, rather, consumer should send 2 tokens (in my particular case). 
Basically to make it "arrowhead compliant" provider needs to verify the arrowhead token. In my particular case, I had to modify my provider so it can handle the 2 tokens.
