### ISSUE TITLE
Client Skeleton in C++

### ISSUE THREAD

**Issue by sumi0910** [arrowhead-f/sos-examples-spring#4]
Is the client skeleton used for 4.1.2 based on c++ can be used for 4.1.3 or can we get an example of the client skeleton in c++

**Comment by tsvetlin** [comment]
Hello!

No, it can not be used. In the future there will be a C++ client skeleton. Until then, please use the JAVA one. Or if you would like, you could contribute to the project by creating it.

Best wishes,
Svetlin
