### ISSUE TITLE
Why would the authorization public key be null?

### ISSUE THREAD

**Issue by emanuelpalm** [arrowhead-f/sos-examples-spring#5]
https://github.com/arrowhead-f/sos-examples-spring/blob/89564053492881295900279b50710b4b4ce4dacc/demo-car-provider/src/main/java/eu/arrowhead/client/skeleton/provider/ProviderApplicationInitListener.java#L107-L110

I've downloaded the sos-examples-spring test application, and tried to create a new project that takes inspiration from the provider example application. When trying to start it, the above referenced code, which I've copied as-is, throws that `ArrowheadException`. I suspect it has something to do with that I'm using my own KeyStore and TrustStore.

Please make the error message better reflect what went wrong. Thank you!

**Comment by borditamas** [comment]
Hi Emanuel,

when ssl enabled and tokensecurity filter is set to true in apllication property, then your provider needs to know the public key of authorizaton core system. As in the referenced code, the javadoc of arrowheadService.queryAuthorizationPublicKey() method says  it returns  "...null when the public key core service URI is not known by ArrowheadContext component".  In the demo project we queried the pulic-key service uri with the method: arrowheadService.updateCoreServiceURIs(CoreSystem.AUTHORIZATION). It's javadoc says "Queries and stores the public service URIs ...".

So if you wish,  you can use these provided arrowhead service methods to have the public key of Authorization Core system or you can implement any custom way to get it. But the main thing is, that you will need the authorization public key for using the token security filter.

Br, Tamás

**Comment by emanuelpalm** [comment]
@borditamas And what is an `ArrowheadContext` component? I can tell that is a [`Map<String, Object>`][context], but not what its purpose is or how I am supposed to use it.

Also, how to I ensure that the `updateCoreServiceURIs(CoreSystem.AUTHORIZATION)` call can succeed? When using your `sos-examples-spring` provider demo application, the call must succeed as I don't get any errors. Why would my application fail, where the only major difference from your demo application is that I'm using a different KeyStore?

Thank you.

[context]: https://github.com/arrowhead-f/client-library-java-spring/blob/02461765cc1eff7d2b3d2ead9b9de71e49765a0a/src/main/java/eu/arrowhead/client/library/config/ApplicationInitListener.java#L50-L54

**Comment by emanuelpalm** [comment]
@borditamas Would public key/certificate issues be enough for a system to be considered "not available"? Anyhow. Thank you for your help. I'll guess I have to keep reading source code.

If you, at some point, could write a guide that includes how to set up a completely new provider/producer system, I believe many AHF newcomers would be thankful. ;-)

**Comment by borditamas** [comment]
please check this ReadMe section of [client-skeleton](https://github.com/arrowhead-f/client-skeleton-java-spring/blob/master/README.md#best-practices-to-start-with-the-skeletons).
If you miss someting from here please give us a hint about.

Thanks!
