### ISSUE TITLE
Guide for creating trust and key stores.

### ISSUE THREAD

**Issue by emanuelpalm** [arrowhead-f/sos-examples-spring#6]
https://github.com/arrowhead-f/sos-examples-spring/blob/89564053492881295900279b50710b4b4ce4dacc/demo-car-provider/src/main/resources/application.properties#L16-L35

I'm currently trying to write my own AHF provider (a.k.a. producer) system, and I understand that my system needs to have its own x.509 certificate. It seems to me as if the key store, referenced in the `application.properties` file shown above, is to contain that certificate, while the trust store, also mentioned above, should contain the certificate that signed the certificates of the arrowhead core systems.

How do I go about this? Does the x.509 certificate of my custom system have be signed by the same root certificate as the core systems? Could you provide a step-by-step guide, not just here but somewhere where everyone can see it. Or perhaps such a guide already exists?

**Comment by borditamas** [comment]
Hello,

as I see you have created an issue in the same topic also in the repo of [core-java-spring](https://github.com/arrowhead-f/core-java-spring/issues/108), therfore I close this ticket.
